# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobileCam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connectedState', models.BooleanField(default=False)),
                ('email', models.EmailField(default='', max_length=254)),
                ('last_name', models.CharField(default='', max_length=70)),
                ('first_name', models.CharField(default='', max_length=35)),
                ('phone_number', models.CharField(default='', max_length=10)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='sessionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('frames', models.IntegerField()),
                ('captured_images', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttux.mobileCam')),
            ],
        ),
        migrations.CreateModel(
            name='sessionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessn_date', models.DateTimeField(verbose_name='Session Date')),
                ('streamId', models.CharField(max_length=50)),
                ('userId', models.CharField(max_length=100)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttux.mobileCam')),
            ],
        ),
    ]
