# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ttux', '0002_auto_20170711_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecam',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttux.MobileCam'),
        ),
        migrations.AlterField(
            model_name='sessionrecord',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttux.MobileCam'),
        ),
    ]
