# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttux', '0003_auto_20180124_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecam',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='mobilecam',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_cam', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttux.MobileCam'),
        ),
        migrations.AlterField(
            model_name='sessionrecord',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttux.MobileCam'),
        ),
    ]
