# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelmedxGroupProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.EmailField(max_length=254)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='telmedxprofile',
            name='user_type',
            field=models.SmallIntegerField(choices=[(1, 'Global Admin'), (2, 'Group Admin'), (3, 'User')], default=3),
        ),
    ]
