# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0003_auto_20180118_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='telmedxuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='telmedxgroupprofile',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.Group'),
        ),
    ]
