# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 19:16
from __future__ import unicode_literals

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180116_2111'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='telmedxuser',
            managers=[
                ('objects', users.models.TelmedxUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='telmedxuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='telmedxuser',
            name='last_name',
        ),
    ]
