# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-08 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_telmedxgroupprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telmedxuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
